# Generated by Django 4.0.4 on 2022-04-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custID', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('login', models.TextField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
            ],
        ),
    ]
